name    'domcleal-katellovirt'
version '0.2.3'
source 'git://github.com/domcleal/katellovirt'
author 'Dominic Cleal'
license 'Apache License, Version 2.0'
summary 'Installs a libvirt hypervisor for testing provisioning'
description 'Installs a libvirt hypervisor for testing provisioning'
project_page 'https://github.com/domcleal/katellovirt'

dependency 'domcleal/augeasproviders', '>= 1.0.1'
dependency 'thias/libvirt', '>= 0.2.3'
dependency 'puppetlabs/firewall'
dependency 'puppetlabs/stdlib'
